services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freya
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - datavolume:/data/postgres
volumes:
  datavolume: